"""empty message

Revision ID: 406d990fc3fb
Revises: 786f6c92c039
Create Date: 2021-09-27 19:30:24.867907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406d990fc3fb'
down_revision = '786f6c92c039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actors', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'actors', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'actors', type_='unique')
    op.alter_column('actors', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
